name: Deploy ke Ubuntu Server

on:
  push:
    branches:
      - master  # ganti kalau kamu pakai 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kode
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy Laravel Project
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@103.183.74.167 << 'EOF'
            cd ~/myapp
            git pull origin master
            composer install --no-interaction --prefer-dist --optimize-autoloader
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
          EOF
