name: Deploy ke Ubuntu Server

on:
  push:
    branches:
      - main  # atau 'master', sesuaikan dengan branch-mu

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kode
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, dom, pdo_sqlite, sqlite3

      - name: Install Dependencies
        run: composer install --no-scripts --prefer-dist

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy ke Server JKT (103.183.74.167)
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@103.183.74.167 << 'EOF'
            cd ~/myapp
            git pull origin main
            composer install --no-interaction --prefer-dist --optimize-autoloader
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
          EOF

      - name: Deploy ke Server SGP (103.250.10.33)
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@103.250.10.33 << 'EOF'
            cd ~/myapp
            git pull origin main
            composer install --no-interaction --prefer-dist --optimize-autoloader
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
          EOF
