name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, dom, pdo_sqlite, sqlite3

      - name: Install Dependencies
        run: composer install --no-scripts --prefer-dist

      - name: Copy .env
        run: cp .env.example .env

      - name: Configure Database Connection
        run: |
          sed -i 's/^DB_CONNECTION=.*/DB_CONNECTION=sqlite/' .env
          sed -i 's|^DB_DATABASE=.*|DB_DATABASE=${{ github.workspace }}/database/database.sqlite|' .env

      - name: Generate Key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Create SQLite Database
        run: mkdir -p database && touch database/database.sqlite

      - name: Clear config
        run: php artisan config:clear

      - name: Config Cache
        run: php artisan config:cache

      - name: Run Migrations (if needed)
        run: php artisan migrate --seed --force

      - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
        run: php artisan test

      - name: Show Laravel logs if failed
        if: failure()
        run: cat storage/logs/laravel.log || echo "No laravel log found"
