name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: mbstring, dom, pdo_sqlite, sqlite3

      - name: Copy .env
        run: cp .env.example .env

      - name: Generate Key
        run: php artisan key:generate

      - name: Install Dependencies
        run: composer install --no-scripts --prefer-dist

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Create SQLite Database
        run: touch database/database.sqlite

      - name: Configure Database Connection
        run: echo "DB_CONNECTION=sqlite" >> .env && echo "DB_DATABASE=${PWD}/database/database.sqlite" >> .env

      - name: Config Cache
        run: php artisan config:cache

      - name: Run Migrations (if needed)
        run: php artisan migrate --seed --force

      - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
        run: php artisan test
